// ─── Module 5 | AI-Generated — SauceDemo Login ────────────────────────────────
// THIS FILE WAS AI-GENERATED by scripts/generate-spec.js using Claude claude-sonnet-4-6.
//
// Pillar 1 demonstration: given a plain-English description of the SauceDemo
// login page, the AI produced a complete, runnable Cypress spec that follows
// all project conventions (POM imports, fixture usage, testIsolation: false,
// before/beforeEach reset pattern).
//
// To regenerate:
//   ANTHROPIC_API_KEY=sk-ant-... node scripts/generate-spec.js
//
// Do not edit this file manually — it is an AI output artifact.
// The generate script will overwrite any manual changes on the next run.

import LoginPage from '../../pages/LoginPage'

describe('Module 5 | AI-Generated — SauceDemo Login', { testIsolation: false }, () => {
  before(() => {
    // Cold-load SauceDemo once. The beforeEach handles all subsequent resets.
    LoginPage.visit()
  })

  beforeEach(() => {
    // Reset to the login form without cy.visit() (avoids SPA routing timeouts).
    // If we're already past login, navigate back via the burger menu.
    cy.url().then((url) => {
      if (url.includes('/inventory') || url.includes('/cart') || url.includes('/checkout')) {
        cy.get('#react-burger-menu-btn').click({ force: true })
        cy.get('#logout_sidebar_link').should('be.visible').click()
      }
    })
    cy.get('#login-button').should('be.visible')
  })

  it('logs in successfully with standard_user credentials', () => {
    cy.fixture('users').then((users) => {
      LoginPage.login(users.standard.username, users.standard.password)
      cy.url().should('include', '/inventory')
      cy.get('.title').should('have.text', 'Products')
    })
  })

  it('shows a locked-out error for locked_out_user', () => {
    cy.fixture('users').then((users) => {
      LoginPage.login(users.locked.username, users.locked.password)
      LoginPage.getErrorMessage()
        .should('be.visible')
        .and('contain.text', 'Sorry, this user has been locked out')
    })
  })

  it('shows an error for invalid credentials', () => {
    cy.fixture('users').then((users) => {
      LoginPage.login(users.invalid.username, users.invalid.password)
      LoginPage.getErrorMessage()
        .should('be.visible')
        .and('contain.text', 'Username and password do not match')
    })
  })

  it('shows a validation error when username is missing', () => {
    LoginPage.login('', 'secret_sauce')
    LoginPage.getErrorMessage()
      .should('be.visible')
      .and('contain.text', 'Username is required')
  })

  it('shows a validation error when password is missing', () => {
    LoginPage.login('standard_user', '')
    LoginPage.getErrorMessage()
      .should('be.visible')
      .and('contain.text', 'Password is required')
  })
})
