// ─── scripts/generate-spec.js — AI Test Generation (Pillar 1) ─────────────────
// Demonstrates AI-powered test generation: given a plain-English description of
// a page, ask Claude to write a runnable Cypress spec, then write it to disk.
//
// This script runs outside Cypress — it is a standalone Node.js tool.
//
// Usage:
//   ANTHROPIC_API_KEY=sk-ant-... node scripts/generate-spec.js
//
//   Windows PowerShell:
//   $env:ANTHROPIC_API_KEY="sk-ant-..."; node scripts/generate-spec.js
//
// The generated spec is committed to the repo so CI can run it without the key.
// Re-run this script whenever you want a fresh AI-generated version.

'use strict'

const Anthropic = require('@anthropic-ai/sdk')
const fs        = require('fs')
const path      = require('path')

// ── Output destination ─────────────────────────────────────────────────────────
const OUTPUT_PATH = path.resolve(
  __dirname,
  '../cypress/e2e/module5-ai-qa/14_ai_generated.cy.js'
)

// ── Page description sent to the AI ───────────────────────────────────────────
// A plain-English description of SauceDemo's login page.
// In a real project this could be an HTML snippet, an OpenAPI spec excerpt,
// a Figma annotation, or a user story — the concept is the same.
const PAGE_DESCRIPTION = `
SauceDemo Login Page (https://www.saucedemo.com)

HTML elements:
  <input id="user-name" type="text" placeholder="Username" />
  <input id="password" type="password" placeholder="Password" />
  <input id="input-error" type="submit" value="Login" />
  <div data-test="error" class="error-message-container"> (appears on failed login)

Known test users:
  standard_user / secret_sauce  → successful login, redirects to /inventory.html
  locked_out_user / secret_sauce → locked out, shows error "Sorry, this user has been locked out."
  invalid_user / wrong_password  → shows error "Username and password do not match any user in this service."

Validation errors (empty fields):
  No username → "Epic sadface: Username is required"
  No password → "Epic sadface: Password is required"

After successful login:
  URL contains "/inventory"
  Page title element: <span class="title">Products</span>
`.trim()

// ── System prompt (output format rules) ───────────────────────────────────────
const SYSTEM_PROMPT = `
You are an expert Cypress 13 test automation engineer.
Write a complete, runnable Cypress spec file based on the page description provided.

STRICT RULES — follow every single one:
1. Output ONLY valid JavaScript. No markdown fences, no prose outside of code comments.
2. Use ES6 import syntax: import LoginPage from '../../pages/LoginPage'
3. The LoginPage singleton has these members:
     loginPage.visit()                      — navigates to saucedemo
     loginPage.login(username, password)    — fills form and clicks Login
     loginPage.getErrorMessage()            — returns cy chainable for the error div
     loginPage.dismissError()              — closes the error banner
     loginPage.elements.usernameInput()    — cy.get('#user-name')
     loginPage.elements.passwordInput()    — cy.get('#password')
     loginPage.elements.loginButton()      — cy.get('#login-button')
     loginPage.elements.errorMessage()     — cy.get('[data-test="error"]')
4. describe block: describe('Module 5 | AI-Generated — SauceDemo Login', { testIsolation: false }, () => { ... })
5. Include before() that calls LoginPage.visit() exactly once.
6. Include beforeEach() that resets to the login form:
     - If current URL includes '/inventory' or '/cart', open the burger menu and click logout.
     - Wait for '#login-button' to be visible before proceeding.
7. Write exactly 5 it() blocks:
     a) Successful login with standard_user
     b) Locked-out user error
     c) Invalid credentials error
     d) Missing username validation error
     e) Missing password validation error
8. Use cy.fixture('users') to read credentials for tests a, b, c.
   The fixture shape is: { standard: { username, password }, locked: { username, password }, invalid: { username, password } }
   Tests d and e can pass empty string '' directly since they test validation, not user data.
9. Add a descriptive comment block at the top (after imports) explaining this file was AI-generated by scripts/generate-spec.js.
10. Do NOT use cy.task(), cy.intercept(), cy.reload(), or cy.visit() inside beforeEach.
`.trim()

// ── Main ───────────────────────────────────────────────────────────────────────
async function generateSpec() {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    console.error('ERROR: ANTHROPIC_API_KEY environment variable is not set.')
    console.error('Usage: ANTHROPIC_API_KEY=sk-ant-... node scripts/generate-spec.js')
    process.exit(1)
  }

  const client = new Anthropic.default({ apiKey })

  console.log('Calling Claude API to generate Cypress spec...')
  console.log(`Model: claude-sonnet-5 | Output: ${OUTPUT_PATH}\n`)

  const message = await client.messages.create({
    model: 'claude-sonnet-5',
    max_tokens: 2048,
    thinking: { type: 'disabled' },
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Generate a Cypress spec for this page:\n\n${PAGE_DESCRIPTION}`,
      },
    ],
  })

  const generatedCode = message.content[0].text

  // Ensure the output directory exists (idempotent).
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  fs.writeFileSync(OUTPUT_PATH, generatedCode, 'utf8')

  console.log('Done.')
  console.log(`Tokens used — input: ${message.usage.input_tokens}, output: ${message.usage.output_tokens}`)
  console.log(`\nSpec written to:\n  ${OUTPUT_PATH}`)
  console.log('\nVerify it runs with:')
  console.log('  npx cypress run --spec cypress/e2e/module5-ai-qa/14_ai_generated.cy.js')
}

generateSpec().catch((err) => {
  console.error('Generation failed:', err.message)
  process.exit(1)
})
